language: c
addons:
  ssh_known_hosts:
  - farm.yourbase.io
  - github.com
  - 159.203.113.62
before_install:
- umask 077
- openssl aes-256-cbc -K $encrypted_0cd90c634a58_key -iv $encrypted_0cd90c634a58_iv
  -in yb_test_id_rsa.enc -out .yb-key -d
- rsync -L -e "ssh -i .yb-key" "microclusters@159.203.113.62:/rembuild" rembuild < /dev/null
script:
- "./rembuild script"
after_success:
- "./rembuild deploy"
