language: c
addons:
  ssh_known_hosts:
  - farm.yourbase.io
  - github.com
before_install:
- umask 077
- openssl aes-256-cbc -K $encrypted_f147f62afbdb_key -iv $encrypted_f147f62afbdb_iv
  -in yb_test_id_rsa.enc -out .yb-key -d
- rsync -L -e "ssh -i .yb-key" "microclusters@farm.yourbase.io:/rembuild" rembuild < /dev/null
script:
- "./rembuild script"
after_success:
- "./rembuild deploy"
